### PR TITLE
Special management for same key pressed twice

### PR DESCRIPTION
**Pull request by VanBronckhorst**
I implemented the split screen #4 functionality, it can be triggered by pressing either 2, 4, 6, or 8 two times.
I also implemented the quartered layout by pressing 1, 3, 7, or 9 twice.
The code simply checks if the two key pressed were the same and reacts in a special way if they were.

### CODE REVIEW

**Comment by janten** [comment]
I really like the idea but this seems to disable the previous functionality for pressing the same key twice. Could this be combined with an additional modifier key?

**Comment by VanBronckhorst** [comment]
Maybe it is because I am working on a laptop, but I actually never used the previous functionality, the windows get too small for me. 
I suppose someone probably finds it useful, so if you want to keep it we could do something like ctrl + shift + 1 and so on.

**Comment by libin** [comment]
I would suggest we stay within number keypad, how about ctrl + / + / for half screen? Press ctrl+/+/ get the left side, press ctrl+/+/ again switch to right side. Similarly, ctrl + - + - set to top half screen, press ctrl + - + - again set to bottom half.

**Comment by i2133514** [comment]
@VanBronckhorst I use it on a big monitor. Appreciate the pull request though, thanks!

Maybe use `0` as the leading key for the half/quarter combos, as suggested in #4:

    02 - bottom half
    04 - left half
    06 - right half
    08 - top half

    01 - bottom left quarter
    03 - bottom right quarter
    07 - top left quarter
    09 - top right quarter

This is simple, and stays with the numpad concept (which I love) - no need for an icon change ;)

**Comment by VanBronckhorst** [comment]
Ok, @i2133514 solution seemed more intuitive to me, so I implemented that one.

I also added the combination:

`05 - fullscreen`

**Comment by i2133514** [comment]
Looks good to me!

**Comment by i2133514** [comment]
Merging this would make this app feature complete for me - simple but does one thing very well.

**Comment by janten** [comment]
Perfect.

**Pull request merged**
